qlik-oss/sn-pivot-table

- src/hooks/use-data-model.ts
- src/pivot-table/data/__tests__/extract-left.test.ts
- src/pivot-table/data/__tests__/extract-top.test.ts
- src/pivot-table/data/__tests__/index.test.ts
- src/pivot-table/data/extract-left.ts
- src/pivot-table/data/extract-top.ts
- src/pivot-table/data/index.ts
- src/types/QIX.ts
Fixes an issue where the number of columns/rows would be wrong given that the user expanded a dimension on a page, then expanded a dimension on an another page, after which they scrolled back to the first page and collapsed the dimension.
A new "page" is loaded when the user scroll so that new data must be fetched.
> fix: number of left columns and top rows would sometimes by wrong

- package.json
- src/contexts/SelectionsProvider.tsx
- src/hooks/__tests__/use-selections-model.test.ts
- src/hooks/use-data-model.ts
- src/hooks/use-expand-or-collapser.ts
- src/hooks/use-nebula-callback.ts
- src/hooks/use-selections-model.ts
- src/index.ts
- src/pivot-table/Root.tsx
- src/pivot-table/components/CellFactory.tsx
- src/pivot-table/components/DataGrid.tsx
- src/pivot-table/components/DimensionCell.tsx
- src/pivot-table/components/HeaderGrid.tsx
- src/pivot-table/components/PivotTable.tsx
- src/pivot-table/components/PseudoDimensionCell.tsx
- src/pivot-table/components/__tests__/CellFactory.test.tsx
- src/pivot-table/components/__tests__/DimensionCell.test.tsx
- src/pivot-table/components/__tests__/PseudoDimensionCell.test.tsx
- src/types/QIX.ts
- src/types/types.ts
- yarn.lock
Add support for selection by clicking on a dimension value. There is room for improvements on the implementation, most notably by reducing the complexity of the DimensionCell component and handling styling better. But that will have to be for targeted for another PR. I did end up using a context to provide the selections model api to components needing it. It had the lowest number of re-renders when I debug different approaches. Thought I expect that might change in the future as more features are added.
- A cell cannot be selected if dimension is locked 
- A cell cannot be selected if a cell from the opposite side (top or left) is already selected
- A cell cannot be selected if an active selection is on another row or column
- A cell cannot be expanded/collapsed while selection mode is …
> feat: selections

- src/hooks/__tests__/use-column-width.test.ts
- src/hooks/__tests__/use-measure-text.test.ts
- src/hooks/use-column-width.ts
- src/hooks/use-data-model.ts
- src/hooks/use-measure-text.ts
- src/pivot-table/components/DataGrid.tsx
- src/pivot-table/components/HeaderGrid.tsx
- src/pivot-table/components/LeftGrid.tsx
- src/pivot-table/components/PivotTable.tsx
- src/pivot-table/components/TopGrid.tsx
- src/pivot-table/components/__tests__/CellFactory.test.tsx
- src/pivot-table/components/__tests__/DimensionCell.test.tsx
- src/types/types.ts
Adds a sizing logic to columns. Where those dimension column on the left is based of approach glyph count, the data column are either based on glyph count, approx. title width, min width or size available.
> feat: dynamic column width

- src/constants/index.ts
- src/pivot-table/components/CellFactory.tsx
- src/pivot-table/components/TotalsCell.tsx
- src/pivot-table/components/__tests__/CellFactory.test.tsx
- src/pivot-table/components/__tests__/TotalsCell.test.tsx
- src/pivot-table/components/shared-styles.ts
Adds support for displaying totals value either below or above using the `qShowTotalsAbove` toggle and `qTotalMode = "TOTAL_EXPR"`
> feat: show totals above or below

- .circleci/config.yml
- package.json
Some trouble with Node versions, so had to fiddle a bit. Seems like playwright installs v16 and the new Nebula serve version needs 18. So I set it to >=16 for now.
> chore: enable sys js build

- src/pivot-table/components/cells/DataCell.tsx
- src/pivot-table/components/cells/ListCellFactory.tsx
- src/pivot-table/components/grids/DataGrid.tsx
- src/pivot-table/components/grids/HeaderGrid.tsx
- src/pivot-table/components/grids/LeftGrid.tsx
- src/pivot-table/components/grids/TopGrid.tsx
The usage of `memo()` inside of our grid components like this one for example: https://github.com/qlik-oss/sn-pivot-table/blob/main/src/pivot-table/components/grids/DataGrid.tsx#L104
is not taking effect and my guess is that in each rerender of grids it’s being recreated because it’s just a variable inside of component which does not memoised using `useMemo`  => then react probably ignoring to memoise it and creates a memo component in every rerender
This PR aims to fix it!
> fix: extract memoized component out of functional components

- src/hooks/use-load-data-pages.ts
When a node was expanded or collapsed, all data before it was fetched again so that the scroll position would not be lost. But this would fetch +100 000 rows if a user had scroll to row 100 000 and expanded that node. So not ideal.
This PR removes that code since it is no longer needed after #237 to keep the scroll position. If the user scroll, for example row 100 000 and expand that node. The scroll position is keep there but all those 100k rows above are empty until the user scroll up. At which point the nodes currently rendered on screen are fetched.
> fix: expand or collapse data fetch

- src/pivot-table/components/icons/Minus.tsx
- src/pivot-table/components/icons/Plus.tsx
Fixes an issue where expand and collapse icons would scale down if the cell had long text.
Before:
After:
> fix: icon size

- src/pivot-table/components/grids/HeaderGrid.tsx
- src/pivot-table/data/__tests__/extract-headers.test.ts
- src/pivot-table/data/__tests__/headers-data.test.ts
- src/pivot-table/data/extract-headers.ts
- src/pivot-table/hooks/__tests__/use-data.test.ts
- src/types/QIX.ts
- src/types/types.ts
Extract the dimenssion title cell key from qDimensionInfo instead of using column index.
> fix: dimension title cell key

- src/pivot-table/components/grids/LeftGrid.tsx
- src/pivot-table/components/grids/TopGrid.tsx
- src/pivot-table/components/helpers/get-key.ts
- src/pivot-table/hooks/use-selections-model.ts
I took a look at the duplicate warnings on code climate. There is generally a lot of similar code, a lot due to some of the grids having do to the same things, but with different qTop/qLeft x/y row/col stuff. No real easy way of generalizing without making it hard to read.
We could potentially raise the simiilar-code threshold. But I mean it depends on what we want code climate to do. Catch all errors including things we don't want to change, or have a looser check that might miss some things that actually needs refactoring?
> refactor: fix dupl warnings

- src/pivot-table/components/grids/LeftGrid.tsx
- src/pivot-table/components/grids/TopGrid.tsx
- src/pivot-table/components/helpers/__tests__/get-item-size-handler.test.ts
- src/pivot-table/components/helpers/get-item-size-handler.ts
Moves the functions for handling item size in react-window list compont to a util-file. It allows us to test rather complex logic without running the whole components.
> refactor: item size handler

- src/pivot-table/components/grids/DataGrid.tsx
- src/types/qlik-chart-models.d.ts
As discussed some time ago. Change debouncer into a throttler to improve the experience when scrolling while still trying to keep the number of calls to Engine at a healthy level.
> fix: data fetch frequency on scroll

- src/pivot-table/data/__tests__/__snapshots__/extract-top.test.ts.snap
- src/pivot-table/data/extract-top.ts
passing `rowIdx` instead of 0 while creating cells in top grid
> fix: expand top grid issue

- src/pivot-table/components/cells/DimensionCell.tsx
we were passing wrong row coordinates to `isSelected`. it was the same for `isLocked` so this one fixes that as well
> fix: selection in other pages

- src/hooks/__tests__/use-pagination.test.ts
- src/hooks/use-pagination.ts
if you expand rows and consecutively end up having more pages than when you opened the app, collapsing a row in last page may cause to land in a empty page (still being the last page even though having less than that). this happens because of how engine works on expand and collapsing the rows. 
in case of collapsing and page loss, land user in the actual last page. 
Here is the demo for fix:
https://github.com/qlik-oss/sn-pivot-table/assets/29652890/67f53c68-3b06-417f-bc7d-608364753c6c
> fix: missing page

- src/pivot-table/components/cells/DimensionCell.tsx
- src/pivot-table/components/cells/ListCellFactory.tsx
- src/pivot-table/components/cells/__tests__/DimensionCell.test.tsx
- src/pivot-table/components/cells/__tests__/ListCellFactory.test.tsx
- src/pivot-table/components/helpers/__tests__/get-item-size-handler.test.ts
- src/pivot-table/components/helpers/get-item-size-handler.ts
- src/pivot-table/data/__tests__/__snapshots__/extract-left.test.ts.snap
- src/pivot-table/data/__tests__/__snapshots__/extract-top.test.ts.snap
- src/pivot-table/data/extract-left.ts
- src/pivot-table/data/helpers/assign-distance-to-next-cell.ts
- src/pivot-table/data/helpers/create-cell.ts
- src/pivot-table/data/left-dimension-data.ts
- src/pivot-table/data/top-dimension-data.ts
- src/types/types.ts
with this change, in a Cell object:
`x` reflects the x index of row in entire dataset
`y` reflects the y index of row in entire dataset
`pageX` reflects x index of row in page (currently its value is same as `x` -> because we don't have horizontal pagination)
`pageY` reflects y index of row in page
> refactor: `dataY` and `y`

- src/pivot-table/components/cells/DimensionCell.tsx
- src/pivot-table/components/cells/__tests__/DimensionCell.test.tsx
- src/pivot-table/components/cells/utils/get-dimension-cell-style.ts
- src/pivot-table/data/__tests__/__snapshots__/extract-left.test.ts.snap
- src/pivot-table/data/__tests__/__snapshots__/extract-top.test.ts.snap
- src/pivot-table/data/__tests__/extract-left.test.ts
- src/pivot-table/data/__tests__/extract-top.test.ts
- src/pivot-table/data/__tests__/left-dimension-data.test.ts
- src/pivot-table/data/__tests__/top-dimension-data.test.ts
- src/pivot-table/data/extract-left.ts
- src/pivot-table/data/extract-top.ts
- src/pivot-table/data/helpers/create-cell.ts
- src/pivot-table/data/left-dimension-data.ts
- src/pivot-table/data/top-dimension-data.ts
- src/pivot-table/hooks/__tests__/use-data.test.ts
- src/pivot-table/hooks/use-data.ts
- src/services/__tests__/layout-service.test.ts
- src/services/layout-service.ts
- src/services/utils/get-sorted-dimension-info.ts
- src/types/QIX.ts
- src/types/types.ts
Fixes an issue where the background styling for a locked dimension was not rendered when the pseudo dimension was not at either the last row or column.
Also included:
* A minor performance improvement as the logic for checking if a cell is locked by the dimension is no longer run at every render. Instead only when new layout is received.
* `background` and `backgroundImage` style properties did not work well together in the DimensionCell component. Now only `background` is used.
TODO for another PR:
* Improve the support for custom background colors. Currently the background for a locked dimension does not take the background set by theme or styling panel into account.
* Remove `dimensionInfoIndexMap` as it should no longer be needed.
Before:
After:
> fix: locked dimension styling

- src/hooks/__tests__/use-effective-properties.test.ts
- src/hooks/use-effective-properties.ts
- src/hooks/use-layout-service.ts
- src/hooks/use-load-data-pages.ts
- src/hooks/use-render.ts
- src/services/__tests__/layout-service.test.ts
- src/services/layout-service.ts
- src/types/types.ts
Adding a hook to fetch effective properties so that the value `qShowTotalsAbove` can be read. It's needed for the "Total at bottom/top" feature.
> feat: use effective properties

- package.json
When you want to debug a failing rendering test locally. This script allows you to start up the rendering server and navigate to `http://localhost:8000/render?fixture=./scenario_1.fix.js` to debug the failing fixture.
> chore: start fixture script

- core/package.json
- package.json
Not sure why different major versions was allowed. Unless someone knows a good reason for it suggest we limit it to minor range.
> chore: limit the peer deps to minor and patch range

- jest.config.js
- jest/setup.js
- jest/setup.ts
When building using nebula using the `build` or `serve` command. A bunch of warnings where logged for missing types from `@testing-library/jest-dom`. This PR attempts to fix that. I'm not entirely sure why the recently started to appear.
Some of the warnings logged:
```
(typescript plugin) src/pivot-table/components/cells/__tests__/DimensionTitleCell.test.tsx (19:34) @rollup/plugin-typescript TS2339: Property 'toBeInTheDocument' does not exist on type 'JestMatchers<HTMLElement>'.
(typescript plugin) src/pivot-table/components/cells/__tests__/DimensionTitleCell.test.tsx (20:38) @rollup/plugin-typescript TS2339: Property 'toHaveStyle' does not exist on type 'JestMatchers<HTMLElement>'.
(typescript plugin) src/pivot-table/components/cells/__tests__/EmptyCell.test.tsx (19:15) …
```
> chore: nebula build typescript warnings

- src/pivot-table/hooks/__tests__/use-column-width.test.ts
- src/pivot-table/hooks/__tests__/use-measure-text.test.ts
- src/pivot-table/hooks/use-column-width.ts
- src/pivot-table/hooks/use-measure-text.ts
- src/types/types.ts
Basically breaking out this: https://github.com/qlik-oss/sn-pivot-table/pull/287/files#diff-ec18bf142eff172651b535422a1a8fa75c79d87588adbc461acef39767dc630eR42-R43. Will be more needed as of that PR, since we take more styling into account.
Passing the whole styling object since we always use the size and fontFamliy from a specific part of the chart (rowContent, header etc). This would also simplify if we would need other styling as well, potentially bold for example
> refactor: smarter args for measure text

- src/pivot-table/components/__tests__/shared-styles.test.ts
- src/pivot-table/components/grids/DataGrid.tsx
- src/pivot-table/components/grids/LeftGrid.tsx
- src/pivot-table/components/grids/TopGrid.tsx
- src/pivot-table/components/shared-styles.ts
Since there will be `showLastColumnBorderRight` arg to the border func added with the column width, it started to become a lot of if statements. Turns out you could simplify it quite a lot
> refactor: simpler logic for border width

- src/pivot-table/components/cells/DimensionCell.tsx
- src/pivot-table/components/cells/__tests__/DimensionCell.test.tsx
There are two interactions state, `active` and `select`, which should turn off selections. This PR fixes so that `select` now also works.
> fix: respect interactions select state

- src/hooks/__tests__/use-load-data-pages.test.ts
- src/hooks/__tests__/use-pagination.test.ts
- src/hooks/use-load-data-pages.ts
- src/hooks/use-pagination.ts
- src/hooks/use-view-service.ts
- src/pivot-table/components/Pagination.tsx
- src/pivot-table/components/PivotTable.tsx
- src/pivot-table/components/__tests__/Pagination.test.tsx
- src/pivot-table/components/__tests__/Wrapper.test.tsx
- src/pivot-table/data/__tests__/extract-left.test.ts
- src/pivot-table/data/__tests__/left-dimension-data.test.ts
- src/pivot-table/data/__tests__/measure-data.test.ts
- src/pivot-table/data/extract-left.ts
- src/pivot-table/data/left-dimension-data.ts
- src/pivot-table/data/measure-data.ts
- src/pivot-table/hooks/__tests__/use-data-model.test.ts
- src/pivot-table/hooks/__tests__/use-data.test.ts
- src/pivot-table/hooks/use-data-model.ts
- src/pivot-table/hooks/use-selections-model.ts
- src/types/types.ts
Unifies the `sn-table` and `sn-pivot-table` PageInfo type. So that it can be used by the Pagination Footer component at a later point.
> refactor: change name from currentPage to page

- src/hooks/__tests__/use-pagination.test.ts
- src/hooks/use-pagination.ts
- src/pivot-table/components/PivotTable.tsx
- src/pivot-table/components/__tests__/Pagination.test.tsx
- src/pivot-table/components/grids/LeftGrid.tsx
- src/pivot-table/data/left-dimension-data.ts
- src/types/types.ts
Uses the actual number of rows in a page instead of the maximum possible when computing some values. I ended up putting the value for that on `PageInfo` as a way to make it easily shared across components/hooks.
Issue that have been fixed:
> fix: columns in left grid out of sync

- src/pivot-table/components/cells/__tests__/DimensionCell.test.tsx
- src/pivot-table/components/cells/utils/get-dimension-cell-style.ts
https://github.com/qlik-oss/sn-pivot-table/assets/29652890/7ecd4fd0-d5da-47a9-9ba9-413fb584b146
> chore: locked cells now keeps the original background color

- src/pivot-table/components/containers/ScrollableContainer.tsx
The idea here is to prevent triggering the browser going back/forward when scrolling the in the pivot table. Using `overscroll-behavior-x` to allow scrolling along the Y axis when the end of the scrollarea is reached. This could for example be on an extended sheet where it would allow scrolling down the sheet once the bottom of the pivot table is reached.
This should work for both mouse wheel and trackpad.
> fix: overscroll behavior

- src/pivot-table/hooks/use-data-model.ts
Fixes an issue where data would not be loaded because it was aborted due to `isLoading` was true. This would lead to empty cell being displayed because data was never fetched for those cells.
It could happen if `getHyperCubePivotData` was slow. I tested that by artificially adding a delay on it.
> fix: slow load more data

- nebula.config.js
- src/ext/property-panel/settings/styling-panel/content.ts
- src/ext/property-panel/settings/styling-panel/grid.ts
- src/pivot-table/__tests__/test-with-providers.tsx
- src/pivot-table/components/cells/PseudoDimensionCell.tsx
- src/pivot-table/components/cells/utils/get-dimension-cell-style.ts
- src/pivot-table/components/cells/utils/get-measure-cell-style.ts
- src/pivot-table/contexts/__mocks__/StyleProvider.tsx
- src/services/__tests__/style-service.test.ts
- src/services/style-service.ts
- src/types/QIX.ts
- src/types/types.ts
As discussed with UX. Move the "line count" styling from the Grid, to the Content section.
Also renames the variable from `lineCount` to `lineClamp`.
TODO in sense themes:
- Update all themes
> fix: rename and move line count

- src/pivot-table/components/cells/__tests__/__mocks__/data-model-mock.ts
- src/pivot-table/hooks/__tests__/use-data-model.test.ts
- src/pivot-table/hooks/use-data-model.ts
- src/pivot-table/hooks/use-mutable-prop.ts
- src/types/types.ts
Fixes an issue where data from previous page could end up on the new page.
It could be reproduces in the following way:
1. Go to last page
2. Scroll down to bottom. Should be more than 50 rows on the page and the call to `getHyperCubePivotData` have to be slow.
3. Go to first page.
Now the data from the last page would be rendered on the first page.
> fix: change page while loading data

- src/pivot-table/components/cells/DimensionTitleCell.tsx
- src/pivot-table/components/cells/styles.tsx
fix for this: 
https://github.com/qlik-oss/sn-pivot-table/assets/29652890/efd8db39-79cb-4f8b-b0cc-1643b80b052a
> fix: prevent clickable head cell for pseudo dims

- src/pivot-table/data/helpers/__tests__/get-expression-color.test.ts
- src/pivot-table/data/helpers/get-expression-color.ts
Make the text color for a cell with "dark" AND "light" background color hard-coded to improve readability.
Note: that it only applies to cells that get the background color from an expression.
> fix: contrasting color for light background

- src/services/__tests__/style-service.test.ts
- src/services/style-service.ts
Measure labels and measure values has per design spec the same default color.
> fix: default measure labels color

- src/pivot-table/components/shared-styles.ts
- src/services/style-service.ts
Changes so that the default text color is resolved from the sprout color palette instead of being hard-coded in sn-pivot-table repo.
Currently the colors are the same and I would guess not really expected to change any time soon.
> fix: primary text color

- src/pivot-table/hooks/__tests__/use-data-model.test.ts
- src/pivot-table/hooks/use-column-width.ts
- src/pivot-table/hooks/use-data-model.ts
- src/types/QIX.ts
Fixes an issue where an error would be thrown when re-sizing the bottom top dimension, if the left side had a pseudo dimension.
Also fixes the type definition. As `columnWidth` does not exist on sn-pivot-tables created in older versions.
> fix: column width error

- src/constants/index.ts
- src/pivot-table/components/PivotTable.tsx
- src/pivot-table/components/grids/HeaderGrid.tsx
- src/pivot-table/components/helpers/get-key.ts
- src/pivot-table/data/__tests__/extract-headers.test.ts
- src/pivot-table/data/__tests__/headers-data.test.ts
- src/pivot-table/data/extract-headers.ts
- src/pivot-table/data/headers-data.ts
- src/pivot-table/hooks/__tests__/use-column-width.test.ts
- src/pivot-table/hooks/__tests__/use-data.test.ts
- src/pivot-table/hooks/use-column-width.ts
- src/pivot-table/hooks/use-data.ts
- src/types/types.ts
To prepare for horizontal headers make column width
use headers data instead of visibleLeftDimensionInfo
Refs: VIZ-2530
> refactor: use headers data for column width

- api-specifications/properties.json
- scriptappy.config.js
- src/qae/initial-properties.js
Adds the defintion for color by expression to the API.
Example on how this color by expression can be defined:
```js
embeded.render({
element: document.querySelector(".object"),
type: "sn-pivot-table",
fields: ["City"],
properties: {
qHyperCubeDef: {
qMode: "P",
qMeasures: [{
qDef: {
qLabel: "Sales Quantity",
qDef: "=Sum([Sales Quantity])",
},
qAttributeExpressions: [
{
qExpression: "=if(Sum([Sales Quantity]) > 500, green(), blue())",
id: "cellBackgroundColor"
},
{
qExpression: "=if(Sum([Sales Quantity]) > 500, white(), yellow())",
id: "cellForegroundColor"
}
],
}],
},
}
});
```
> docs: add color by expression definition

- src/pivot-table/components/cells/utils/get-dimension-cell-style.ts
the lock cell background is behaves differnetly in very big cell sizes (maybe over 30k px), this pr fixes it
in below examples i just stretch the cell width manually but i saw some nodes with very large children which i noticed the bug on it
Before: 
https://github.com/qlik-oss/sn-pivot-table/assets/29652890/3c57d127-5e00-4cb9-8362-176c59da651d
After: 
https://github.com/qlik-oss/sn-pivot-table/assets/29652890/340dece5-8457-4eb5-9a70-e64ce2859496
> fix: lock bg issue

- src/pivot-table/components/cells/styles.tsx
- src/pivot-table/components/icons/Minus.tsx
- src/pivot-table/components/icons/Plus.tsx
- src/pivot-table/components/icons/styles.ts
- src/pivot-table/components/shared-styles.ts
- src/pivot-table/constants.ts
Plus/minus icon shrinking in the size when text requires bigger space. This PR fixes it.
Before: 
After:
> fix: plus minus icon size

- src/pivot-table/hooks/__tests__/use-selections-model.test.ts
- src/pivot-table/hooks/use-selections-model.ts
getAttribute("class") can return a string with multiple classes, so using `includes` instead. This also works when the class is `sn-pivot-table-column-adjuster-border`
> fix: proplery check for adjuster class

- src/pivot-table/components/__tests__/shared-styles.test.ts
- src/pivot-table/components/shared-styles.ts
Fixes a react warning that could occur when switching themes. Reproduced by switching between "Default" and "Only transparent borders" theme in Nebula dev.
> Warning: Updating a style property during rerender (borderColor) when a conflicting property is set (borderBottomColor) can lead to styling bugs. To avoid this, don't mix shorthand and non-shorthand properties for the same value; instead, replace the shorthand with separate values.
> fix: react border color warning

- src/pivot-table/components/cells/DimensionValue/ExpandOrCollapseIcon.tsx
- src/pivot-table/components/cells/DimensionValue/StickyCellContainer.tsx
- src/pivot-table/components/cells/DimensionValue/Text.tsx
Allows cell that are expanded to have text on multiple lines.
marginTop is need on left side to put the Icon aligned at the center of the first row. Previously this was handled by `alignItems: center` in `StickCellContainer.tsx`. Now it have to be manually positioned.
Before:
After:
> fix: text line clamp for expanded cell

- src/pivot-table/components/cells/DimensionValue/Container.tsx
Last col is now expandable
https://github.com/qlik-oss/sn-pivot-table/assets/29652890/0f0b3303-cdca-42fd-9cbf-c2b88ce2c3e6
> fix: last col cannot be expanded

- package.json
- src/pivot-table/components/cells/ColumnAdjusterWrapper.tsx
- src/pivot-table/components/cells/DimensionTitleCell.tsx
- src/pivot-table/components/cells/DimensionValue/Container.tsx
- src/pivot-table/components/cells/DimensionValue/index.tsx
- src/pivot-table/components/cells/__tests__/ColumnAdjusterWrapper.test.tsx
- src/pivot-table/hooks/__tests__/use-head-cell-dim.test.ts
- src/pivot-table/hooks/use-head-cell-dim.ts
- src/pivot-table/hooks/use-is-adjusting-width.ts
- yarn.lock
In order to block click events on the dimension value cells and header cells, we need to know when the column adjuster is being dragged or not. Therefor we add a `isAdjustingWidth` state, the setter to the `ColumnAdjuster` and set it to true when you start dragging. The state is reset if there is a layout change, so you can select/open the header menu again. Note that there is still a small bug you can get. If you have the min width aldready, then start to drag over the cell and release, you will trigger the cell click handler. This is an extreme corner-case, that will be fixed if we implement drag to select. See both the fix and the remaining bug in the gif
[This](https://github.com/qlik-oss/nebula-table-utils/pull/76) change in utils repo needs to be released before merging this PR
> fix: prevent click event when dragging

- src/pivot-table/components/cells/ColumnAdjusterWrapper.tsx
- src/pivot-table/data/extract-headers.ts
- src/types/types.ts
- don't render the column adjuster for row headers
- set `colIdx` and use it for `overrideLeftGridWidth`. Now `colIdx` is used to set `activelySortedColumn`, which in turn determines some states in the header menu. That is still not correct and needs to be fixed in a different PR. This is still an improvement of what it was before.
I tried to test this, but to get a correct `isLeftDimension`, we need to mock more or less all of `layoutService`. We might want to do that in a smart way, but that is a different PR
> fix: only render columnadjuster for headers that are left dimensions + correctly override widths on the left side

- src/hooks/__tests__/use-load-data-pages.test.ts
- src/hooks/use-load-data-pages.ts
- src/hooks/use-render.ts
- src/pivot-table/components/grids/DataGrid.tsx
- src/pivot-table/hooks/use-data-model.ts
- src/utils/__tests__/handle-max-engine-size.test.ts
- src/utils/handle-max-engine-size.ts
Fixes an issue where empty cells could be rendered if more than 50 rows and/or 50 columns was visible in the pivot table. The `onItemsRendered` callback would fetch addtional data on the first render of the chart. But when a update was made that triggered a new layout, empty cells would be rendered as `onItemsRendered` was no longer called.
This also fixes an issue in `onItemsRendered` where it could call Engine to request data that exceeded the max limit of 10k data values.
> fix: render empty cells

- src/hooks/use-load-data-pages.ts
- src/hooks/use-mutable-nebula-prop.ts
- src/hooks/use-nebula-ref.ts
Fixes an issue where the chart would be flickering when it was being resized.
Before:
https://github.com/qlik-oss/sn-pivot-table/assets/16608020/b5f88f4f-98ff-4242-98c3-807f9c953323
After:
https://github.com/qlik-oss/sn-pivot-table/assets/16608020/8e1720b0-d0a5-4b96-ad3f-50dfe201237f
> fix: resize flickering

- src/pivot-table/components/grids/HeaderGrid.tsx
As for the top grid, the z-index is needed to make sure the column adjuster overlaps two cells.
> fix: use increasing z-index for header grid cells

- src/pivot-table/hooks/use-column-width/__tests__/use-column-width.test.ts
- src/pivot-table/hooks/use-column-width/use-column-width-left.ts
Fixes an issue where the expand icon was removed from column width calculations. The column was incorrectly marked as the last column and therefore not needing the expand icon
Before:
https://github.com/qlik-oss/sn-pivot-table/assets/968450/492cee38-e694-44e3-8a27-a487a5ba6a09
After:
https://github.com/qlik-oss/sn-pivot-table/assets/968450/707c25bd-c348-4a50-9bb4-78fc41c13f9d
> fix: remove expand icon at last column only

- src/pivot-table/hooks/use-data-model.ts
- src/pivot-table/hooks/use-items-rendered-handler/utils/__tests__/fetch-pages.test.ts
- src/pivot-table/hooks/use-items-rendered-handler/utils/fetch-pages.ts
- src/pivot-table/hooks/use-items-rendered-handler/utils/get-column-pages.ts
- src/pivot-table/hooks/use-items-rendered-handler/utils/get-row-pages.ts
Fixes an issue where data would not be fetch when re-sizing the PVT.
Two reason this happend:
- Both vertical and horizontal scroll direction can be reset to `None` when a PVT is re-sized.
- `isMissingColumnData` logic did not work properly as extracting "rows" from an array using `slice()` does not work if the end index is larger then the size of the array. Ex: `[0, 1, 2].slice(2, 4)` => `[2]`, but for the logic to work it should have been an array like this `[2, undefined]`
https://github.com/qlik-oss/sn-pivot-table/assets/16608020/f6522e6a-3c12-40e4-ae58-22a6e792de1e
> fix: data fetch on resize

- src/pivot-table/components/helpers/__tests__/get-item-size-handler.test.ts
- src/pivot-table/components/helpers/get-item-size-handler.ts
Fixes an issue where the column width was not correctly calculated for the "leaf row" when the last row is an empty row.
Before
https://github.com/qlik-oss/sn-pivot-table/assets/16608020/b3f42ff8-17fd-4d3f-b64d-4baead79bb95
After
https://github.com/qlik-oss/sn-pivot-table/assets/16608020/fcbd9a56-5897-4349-8b5b-560a2c7f40c7
> fix: column width for empty row

- src/ext/property-panel/settings/styling-panel/utils/__tests__/create-color-picker-item.test.ts
- src/ext/property-panel/settings/styling-panel/utils/create-color-picker-item.ts
The color picker in Sense does not support `transparent` color value. To get around that we can use `none` instead, which can be shown as a selected value in the color picker.
After:
> fix: transparent color in color picker

- src/pivot-table/components/__tests__/shared-styles.test.ts
- src/pivot-table/components/shared-styles.ts
Before border settings `width` and `color` was explicitly set for each side (eg. `borderLeftWidth: 1`) and then `borderStyle: solid` for all sides. Now we set `borderLeft/Right/Top/Bottom` with width, style and color. if there is no border it is just `"none"`
> fix: set border explicitly for each side

- src/services/__tests__/style-service.test.ts
- src/services/style-service.ts
Fixes an issue where setting the color for "border" and "divider" via the Styling panel to "none", would cause the borders to render with `currentcolor` producing some unexpected results.
Background color and font color appears to be working with `none` as color but this PR fixes those scenarios as well. As `none` is not a valid css color value.
Before:
https://github.com/qlik-oss/sn-pivot-table/assets/16608020/246a71e9-c01f-4a65-a017-d0671c19fe6c
After:
https://github.com/qlik-oss/sn-pivot-table/assets/16608020/c8260424-43c8-4153-b4f7-9fb64d24746a
> fix: none color

- src/pivot-table/components/shared-styles.ts
Fixes an issue where "random" bottom border would appear. For this to happend, the totals at bottom had to be enabled and the bottom total rows had to be visible before expanding a cell. It also only occured in Firefox.
What would happen is that the border for the cells at row Y would go from having border styling set via `borderBottomColor` (from total divider border) to having border styling via `borderBottom`. This would cause bottom border to loose it's color for the bottom border.
There will be another PR that will fix the root cause of this issue which is that cells in the DataGrid gets a key that is generated from row and column index. This should instead be unique per data value.
React warning when it happend:
Before:
https://github.com/qlik-oss/sn-pivot-table/assets/16608020/17111 …
> fix: random bottom color

- src/pivot-table/components/PivotTable.tsx
- src/pivot-table/hooks/use-column-width/__tests__/use-column-width.test.ts
- src/pivot-table/hooks/use-column-width/index.ts
- src/pivot-table/hooks/use-column-width/types.ts
- src/pivot-table/hooks/use-column-width/use-column-width-left.ts
- src/pivot-table/hooks/use-column-width/use-column-width-right.ts
The goal with this PR is that **nothing returned from the `useColumnWidth` hook should change (new value or instance), when we need the pivot table to be performant**. By performant I mean doing interactions with the chart, not editing it (then a full rerender is totally OK). For that I include
- selections
- scrolling
- sorting
- column resize
The resize will trigger a update in any case, for obvious reasons. Sorting fetches new data, so that one is hard to prevent. But for scrolling and selections, there should be no new values or instances returned. So now the properties returned from this hook, wont trigger any rerenders for the child components of `PivotTable`
What I've changed:
- only passing the `tableWidth`, the height is not relevant
- removing useMemo for values that are cheap …
> perf(useColumnWidth): remove overuse of memoization and make no unnesceary updates of return values

- src/pivot-table/components/grids/LeftGrid.tsx
- src/pivot-table/components/grids/TopGrid.tsx
- src/pivot-table/components/helpers/__tests__/get-item-size-handler.test.ts
- src/pivot-table/components/helpers/get-item-size-handler.ts
- src/pivot-table/hooks/use-column-width/use-column-width-right.ts
Did some profiling with a large number of dimensions in either Top or Left grid. The 3 calls that stood out as costly was calls to `Object.values` and `toFixed`, both methods where called for each cell in every react window list on every render.
- For `Object.values` the solution was to use the already resolved `listValues`
- There was no need to call `toFixed` everytime `getRightGridColumnWidth` was called. So simple moved that logic out
> perf: reduce usage of Object.values

- src/pivot-table/components/cells/DataCell.tsx
- src/pivot-table/components/cells/__tests__/DataCell.test.tsx
- src/pivot-table/components/grids/DataGrid.tsx
- src/types/types.ts
Noticed an issue will working on #503 that the data grid was not getting the correct size on the last page.
I don't think it will fix any noticable issue until it's merged with #503, there this issue extra data fetch calls on the last page.
> fix: data grid row count

- src/pivot-table/components/helpers/get-item-size-handler.ts
- src/pivot-table/hooks/__tests__/use-data.test.ts
- src/pivot-table/hooks/use-attr-expr-info-indexes.ts
- src/pivot-table/hooks/use-column-width/__tests__/use-column-width.test.ts
- src/pivot-table/hooks/use-column-width/use-column-width-left.ts
- src/pivot-table/hooks/use-column-width/use-column-width-right.ts
- src/pivot-table/hooks/use-data-model.ts
- src/pivot-table/hooks/use-data.ts
- src/services/__tests__/layout-service.test.ts
- src/services/layout-service.ts
- src/types/types.ts
It's currently not possible to set a show conditions on measures via the property panel, but by either convering an old PVT to sn-pivot-table or using a mashup with calculated conditions properties it's still possible to get layout with hidden measures.
This PR fixes:
-  An issue that can occur when combining color by expression on a measure and at the same time have a hidden measure before (with lower index) the measure with color by expression.
- An issue that can occur when adjusting the column width of a measure when a hidden measure exist before the adjusted measured. The column width patch would be applied to the wrong qMeasureInfo.
- With pseudo dimension on the left side. The column width would in include hidden measures, potentially having great affect on the column width.
- …
> fix: handle hidden measures

- api-specifications/properties.json
- nebula.config.js
- nebula.rendering.config.js
- src/ext/property-panel/data.ts
- src/pivot-table/components/cells/DataCell.tsx
- src/pivot-table/components/cells/DimensionValue/Container.tsx
- src/pivot-table/components/cells/DimensionValue/__tests__/DimensionValue.test.tsx
- src/pivot-table/components/cells/DimensionValue/utils/__tests__/get-justify-content.test.ts
- src/pivot-table/components/cells/DimensionValue/utils/get-justify-content.ts
- src/pivot-table/components/cells/DimensionValue/utils/get-text-align.ts
- src/pivot-table/components/cells/__tests__/DataCell.test.tsx
- src/pivot-table/components/cells/utils/__tests__/get-measure-cell-style.test.ts
- src/pivot-table/components/cells/utils/__tests__/resolve-text-align.test.ts
- src/pivot-table/components/cells/utils/get-measure-cell-style.ts
- src/pivot-table/components/cells/utils/resolve-text-align.ts
- src/qae/initial-properties.js
- src/types/QIX.ts
Adds an option to the property panel to set text alignment for dimensions and measures. The alignment only affects the data values and not the header values.
PP option:
Output:
> feat: text alignment
