qlik-oss/sn-pivot-table

package.json
src/pivot-table/components/DimensionCell.tsx
yarn.lock

Made an arbitrary choice of the icon

feat: expand and collapse icon

---

src/hooks/use-data-loader.ts
src/hooks/use-data-model.ts
src/hooks/use-expand-or-collapser.ts
src/index.ts
src/pivot-table/components/CellFactory.tsx
src/pivot-table/components/DimensionCell.tsx
src/pivot-table/components/PivotTable.tsx
src/types/QIX.ts
src/types/react-window.d.ts
src/types/types.ts

Fixes an issue where the scroll position after expand/collapse would be wrong. Also reduced the number of re-renders in half and it's really time to start adding some tests..

fix: scroll position after expand and collapse

---

.circleci/config.yml
.eslintrc.yml
jest.config.js
jest/setup.js
package.json
src/pivot-table/components/DimensionCell.tsx
src/pivot-table/components/DimensionTitleCell.tsx
src/pivot-table/components/EmptyCell.tsx
src/pivot-table/components/EmptyHeaderCell.tsx
src/pivot-table/components/MeasureCell.tsx
src/pivot-table/components/__tests__/DimensionCell.test.tsx
src/pivot-table/components/__tests__/DimensionTitleCell.test.tsx
src/pivot-table/components/__tests__/EmptyCell.test.tsx
src/pivot-table/components/__tests__/EmptyHeaderCell.test.tsx
src/pivot-table/components/__tests__/MeasureCell.test.tsx
yarn.lock

Add a minimal setup to get going with unit tests and some tests to try it out. More to come other PRs.

test: setup test config and add some tests

---

.eslintrc.yml
src/data.ts
src/hooks/use-data-model.ts
src/hooks/use-expand-or-collapser.ts
src/pivot-table/components/CellFactory.tsx
src/pivot-table/components/DataCell.tsx
src/pivot-table/components/DataGrid.tsx
src/pivot-table/components/DimensionCell.tsx
src/pivot-table/components/FullSizeContainer.tsx
src/pivot-table/components/HeaderGrid.tsx
src/pivot-table/components/LeftGrid.tsx
src/pivot-table/components/ScrollableContainer.tsx
src/pivot-table/components/StickyContainer.tsx
src/pivot-table/components/TopGrid.tsx
src/pivot-table/components/__tests__/CellFactory.test.tsx
src/pivot-table/components/__tests__/DataCell.test.tsx
src/pivot-table/components/__tests__/DimensionCell.test.tsx
src/pivot-table/components/__tests__/DimensionTitleCell.test.tsx
src/pivot-table/components/__tests__/EmptyCell.test.tsx
src/pivot-table/components/__tests__/EmptyHeaderCell.test.tsx
src/pivot-table/data/__tests__/extract-headers.test.ts
src/pivot-table/data/__tests__/extract-left.test.ts
src/pivot-table/data/__tests__/extract-top.test.ts
src/pivot-table/data/extract-headers.ts
src/pivot-table/data/extract-left.ts
src/pivot-table/data/extract-top.ts
src/pivot-table/data/index.ts
src/types/types.ts

Looks like prettier is turning off a bunch of rules I'd like to have on.

chore: lint fixes

---

package.json

same motivation as https://github.com/qlik-oss/sn-table/pull/680

fix: remove module from root package.json

---

src/ext/property-panel/__tests__/settings.test.ts
src/ext/property-panel/settings.ts

basic styling panel for pivot table
https://user-images.githubusercontent.com/29652890/232756424-a94bcdc5-8543-4517-9dbf-31ab9e051052.mov

feat: add general styling panel

---

api-specifications/properties.json
src/qae/initial-properties.d.ts
src/qae/initial-properties.js

chore: api spec update

---

src/services/__tests__/style-service.test.ts
src/services/style-service.ts
src/types/QIX.ts

uses the theme to resolve color, making sure we pick the color from palette when there is a valid index

fix: resolve palette colors

---

core/package.json
package.json
src/locale/__tests__/translations.test.ts
yarn.lock

chore: update nebula to 4.0.0

---

src/locale/locales/de.json
src/locale/locales/es.json
src/locale/locales/fr.json
src/locale/locales/it.json
src/locale/locales/ja.json
src/locale/locales/ko.json
src/locale/locales/nl.json
src/locale/locales/pl.json
src/locale/locales/pt.json
src/locale/locales/ru.json
src/locale/locales/sv.json
src/locale/locales/tr.json
src/locale/locales/zh-CN.json
src/locale/locales/zh-TW.json

chore(translations): UI bus - 2023-05-05
- Update translations related to: 24451bd - feat: locale (#251)

chore(translations): UI bus - 2023-05-05

---

src/pivot-table/Root.tsx
src/pivot-table/__tests__/test-with-providers.tsx
src/pivot-table/contexts/SelectionsProvider.tsx
src/pivot-table/hooks/__tests__/use-selections-model.test.ts
src/pivot-table/hooks/use-selections-model.ts

confirming selection is now resetting page to 0

fix: selection confirm should reset page to the first one

---

renovate.json

Looks like #315 did not do what I hoped. So trying to disable the packages instead.

chore: disable qlik dev tool packages

---

src/pivot-table/components/cells/DimensionTitleCell.tsx

feat: header menu selections

---

src/pivot-table/components/PivotTable.tsx
src/pivot-table/hooks/__tests__/use-scroll.test.ts
src/pivot-table/hooks/use-scroll.ts

Moves the scrolling logic from `PivotTable` component to a custom hook.

refactor: use scroll

---

package.json

fix: remove sprout as peer dep

---

api-specifications/properties.json
src/qae/initial-properties.js
src/types/QIX.ts

Updates the API to adhere to the new components api defined in #404

feat!: new components api

---

src/pivot-table/components/cells/TotalsCell.tsx

fix: totals cell line clamp

---

nebula.config.js
src/ext/property-panel/settings/styling-panel/grid.ts
src/ext/property-panel/settings/styling-panel/large-panal-section.ts
src/ext/property-panel/settings/styling-panel/small-panel-section.ts
src/ext/property-panel/settings/styling-panel/utils/get-theme-value.ts
src/services/style-service.ts
src/types/QIX.ts
src/types/types.ts

Consumes the new theme structure.

feat: new theme structure

---

src/locale/locales/de.json
src/locale/locales/es.json
src/locale/locales/fr.json
src/locale/locales/it.json
src/locale/locales/ja.json
src/locale/locales/ko.json
src/locale/locales/nl.json
src/locale/locales/pl.json
src/locale/locales/pt.json
src/locale/locales/ru.json
src/locale/locales/sv.json
src/locale/locales/tr.json
src/locale/locales/zh-CN.json
src/locale/locales/zh-TW.json

chore(translations): UI bus - 2023-11-17
- Update translations related to: c906c7f - fix: crash when no data exists (#458)

chore(translations): UI bus - 2023-11-17

---

src/pivot-table/components/PivotTable.tsx
src/pivot-table/components/containers/FullSizeContainer.tsx
src/pivot-table/components/containers/StickyContainer.tsx

https://github.com/qlik-oss/sn-pivot-table/assets/29652890/2ad20ae8-0b01-4e3e-b325-6d72e1a11f3d

fix: header grid border issue

---

package.json
src/pivot-table/components/cells/ColumnAdjusterWrapper.tsx
yarn.lock

Fixes the horizontal scrollbar that appears because of the an overflow issue with the column adjuster
Before:
After:

fix: scrollbar from column adjuster overflow

---

package.json
pnpm-lock.yaml

The package was not being used anywhere

chore: remove babel-eslint pkg
